package eu.kanade.tachiyomi.animeextension.id.nontonhentai

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

object NontonHentaiFilters {
    open class QueryPartFilter(
        displayName: String,
        val vals: Array<Pair<String, String>>,
    ) : AnimeFilter.Select<String>(
        displayName,
        vals.map { it.first }.toTypedArray(),
    ) {
        fun toQueryPart(name: String): String {
            val v = vals[state].second
            return if (v.isNotBlank()) "&$name=$v" else ""
        }
    }

    open class CheckBoxFilterList(name: String, values: List<AnimeFilter.CheckBox>) : AnimeFilter.Group<AnimeFilter.CheckBox>(name, values)
    private class CheckBoxVal(name: String, state: Boolean = false) : AnimeFilter.CheckBox(name, state)

    private inline fun <reified R> AnimeFilterList.asQueryPart(name: String): String = (this.getFirst<R>() as? QueryPartFilter)?.toQueryPart(name).orEmpty()

    private inline fun <reified R> AnimeFilterList.getFirst(): R? = this.filterIsInstance<R>().firstOrNull()

    private inline fun <reified R> AnimeFilterList.parseCheckbox(
        options: Array<Pair<String, String>>,
        name: String,
    ): String {
        val group = this.getFirst<R>() as? CheckBoxFilterList ?: return ""
        return group.state
            .mapNotNull { checkbox ->
                if (checkbox.state) {
                    options.find { it.first == checkbox.name }?.second
                } else null
            }.joinToString("&$name[]=").let {
                if (it.isBlank()) "" else "&$name[]=$it"
            }
    }

    class OrderFilter : QueryPartFilter("Urutkan", FiltersData.ORDER)
    class StatusFilter : QueryPartFilter("Status", FiltersData.STATUS)
    class TypeFilter : QueryPartFilter("Tipe", FiltersData.TYPE)
    class SubFilter : QueryPartFilter("Sub", FiltersData.SUB)

    class GenreFilter : CheckBoxFilterList(
        "Genre",
        FiltersData.GENRE.map { CheckBoxVal(it.first, false) },
    )

    class StudioFilter : CheckBoxFilterList(
        "Studio",
        FiltersData.STUDIO.map { CheckBoxVal(it.first, false) },
    )

    class SeasonFilter : CheckBoxFilterList(
        "Season",
        FiltersData.SEASON.map { CheckBoxVal(it.first, false) },
    )

    val FILTER_LIST
        get() = AnimeFilterList(
            AnimeFilter.Header("Catatan: Filter diabaikan jika kolom pencarian diisi"),
            OrderFilter(),
            StatusFilter(),
            TypeFilter(),
            SubFilter(),
            AnimeFilter.Separator(),
            GenreFilter(),
            AnimeFilter.Separator(),
            StudioFilter(),
            AnimeFilter.Separator(),
            SeasonFilter(),
        )

    internal fun getSearchParameters(filters: AnimeFilterList): String {
        if (filters.isEmpty()) return "order="
        val sb = StringBuilder()
        sb.append(filters.asQueryPart<OrderFilter>("order"))
        sb.append(filters.asQueryPart<StatusFilter>("status"))
        sb.append(filters.asQueryPart<TypeFilter>("type"))
        sb.append(filters.asQueryPart<SubFilter>("sub"))
        sb.append(filters.parseCheckbox<GenreFilter>(FiltersData.GENRE, "genre"))
        sb.append(filters.parseCheckbox<StudioFilter>(FiltersData.STUDIO, "studio"))
        sb.append(filters.parseCheckbox<SeasonFilter>(FiltersData.SEASON, "season"))
        return sb.toString().removePrefix("&")
    }

    private object FiltersData {
        val ORDER = arrayOf(
            Pair("Default (Baru Diupdate)", ""),
            Pair("Judul (A-Z)", "title"),
            Pair("Judul (Z-A)", "titlereverse"),
            Pair("Update Terbaru", "update"),
            Pair("Baru Ditambahkan", "latest"),
            Pair("Populer", "popular"),
            Pair("Rating Tertinggi", "rating"),
        )

        val STATUS = arrayOf(
            Pair("Semua", ""),
            Pair("Ongoing", "ongoing"),
            Pair("Completed", "completed"),
            Pair("Upcoming", "upcoming"),
            Pair("Hiatus", "hiatus"),
        )

        val TYPE = arrayOf(
            Pair("Semua", ""),
            Pair("TV Series", "tv"),
            Pair("OVA", "ova"),
            Pair("Movie", "movie"),
            Pair("Live Action", "live action"),
            Pair("Special", "special"),
            Pair("BD", "bd"),
            Pair("ONA", "ona"),
            Pair("Music", "music"),
        )

        val SUB = arrayOf(
            Pair("Semua", ""),
            Pair("Sub (Indo)", "sub"),
            Pair("Dub", "dub"),
            Pair("RAW", "raw"),
        )

        val GENRE = arrayOf(
            Pair("2D", "2d"),
            Pair("3D", "3d"),
            Pair("3P", "3p"),
            Pair("4HR+Other Asian", "4hrother-asian"),
            Pair("4P", "4p"),
            Pair("abuse", "abuse"),
            Pair("Acme · Orgasm", "acme-%c2%b7-orgasm"),
            Pair("Acme Orgasm", "acme-orgasm"),
            Pair("Action", "action"),
            Pair("Adult Cast", "adult-cast"),
            Pair("Adventure", "adventure"),
            Pair("Affair", "affair"),
            Pair("Ahegao", "ahegao"),
            Pair("Akita Shoten", "akita-shoten"),
            Pair("Amateur", "amateur"),
            Pair("Amatir", "amatir"),
            Pair("Anal", "anal"),
            Pair("Anal Sex", "anal-sex"),
            Pair("Android", "android"),
            Pair("Angel", "angel"),
            Pair("Anthropomorphic", "anthropomorphic"),
            Pair("Armpit", "armpit"),
            Pair("ASMR", "asmr"),
            Pair("AV Actress", "av-actress"),
            Pair("Avant Garde", "avant-garde"),
            Pair("Babe", "babe"),
            Pair("Back", "back"),
            Pair("BBW", "bbw"),
            Pair("BDSM", "bdsm"),
            Pair("Beastiality", "beastiality"),
            Pair("Beautiful Girl", "beautiful-girl"),
            Pair("Bestiality", "bestiality"),
            Pair("Bestiallity", "bestiallity"),
            Pair("Big Ass", "big-ass"),
            Pair("Big Boobs", "big-boobs"),
            Pair("Big Breasts", "big-breasts"),
            Pair("Big Butt", "big-butt"),
            Pair("Big Oppai", "big-oppai"),
            Pair("Big Tits", "big-tits"),
            Pair("BigOppai", "bigoppai"),
            Pair("Bigtis", "bigtis"),
            Pair("Bigtits", "bigtits"),
            Pair("Blackmail", "blackmail"),
            Pair("Blow", "blow"),
            Pair("Blow Job", "blow-job"),
            Pair("Blowjob", "blowjob"),
            Pair("Blue Archive", "blue-archive"),
            Pair("Bokep Indo", "bokep-indo"),
            Pair("Bondage", "bondage"),
            Pair("Boys Love", "boys-love"),
            Pair("Bride", "bride"),
            Pair("Brunette", "brunette"),
            Pair("Bukakke", "bukakke"),
            Pair("Bukkake", "bukkake"),
            Pair("Busty fetish", "busty-fetish"),
            Pair("Butt", "butt"),
            Pair("Censored", "censored"),
            Pair("Cheating", "cheating"),
            Pair("Chikan", "chikan"),
            Pair("Comedy", "comedy"),
            Pair("Commedy", "commedy"),
            Pair("Cosplay", "cosplay"),
            Pair("Cowgirl", "cowgirl"),
            Pair("Cowirl", "cowirl"),
            Pair("Cream Pie", "cream-pie"),
            Pair("Creampie", "creampie"),
            Pair("Crossdressing", "crossdressing"),
            Pair("Cuckold", "cuckold"),
            Pair("Cumshot.", "cumshot"),
            Pair("Danmachi", "danmachi"),
            Pair("Dark Skin", "dark-skin"),
            Pair("Debut Production", "debut-production"),
            Pair("Decensored", "decensored"),
            Pair("Deep Throating", "deep-throating"),
            Pair("Demon", "demon"),
            Pair("Demons", "demons"),
            Pair("Detective", "detective"),
            Pair("Digital Mosaic", "digital-mosaic"),
            Pair("DILF", "dilf"),
            Pair("Dirty Words", "dirty-words"),
            Pair("Documentary", "documentary"),
            Pair("Doggy", "doggy"),
            Pair("Doggy style", "doggy-style"),
            Pair("Doggystyle", "doggystyle"),
            Pair("Domination", "domination"),
            Pair("Double Penetration", "double-penetration"),
            Pair("Drag", "drag"),
            Pair("Drama", "drama"),
            Pair("Drug", "drug"),
            Pair("Ecchi", "ecchi"),
            Pair("Elf", "elf"),
            Pair("Embarrassment", "embarrassment"),
            Pair("Entertainer", "entertainer"),
            Pair("Erotica", "erotica"),
            Pair("Escolar", "escolar"),
            Pair("Exhibition", "exhibition"),
            Pair("Exhibitionist", "exhibitionist"),
            Pair("Facials", "facials"),
            Pair("Fantasy", "fantasy"),
            Pair("Fellatio", "fellatio"),
            Pair("Female Monster", "female-monster"),
            Pair("Female teacher", "female-teacher"),
            Pair("Femdom", "femdom"),
            Pair("fetish", "fetish"),
            Pair("Filmed", "filmed"),
            Pair("Flat", "flat"),
            Pair("Footjob", "footjob"),
            Pair("Forced", "forced"),
            Pair("Frontier Works", "frontier-works"),
            Pair("Full Yuri", "full-yuri"),
            Pair("Futanari", "futanari"),
            Pair("Futanari Gangbang", "futanari-gangbang"),
            Pair("Gangbang", "gangbang"),
            Pair("Genshin Impact", "genshin-impact"),
            Pair("Ghost", "ghost"),
            Pair("Girls Love", "girls-love"),
            Pair("Glasses", "glasses"),
            Pair("Gore", "gore"),
            Pair("Grimosa", "grimosa"),
            Pair("Group", "group"),
            Pair("Gyaru", "gyaru"),
            Pair("Hand Job", "hand-job"),
            Pair("Handjob", "handjob"),
            Pair("Hardcore", "hardcore"),
            Pair("Harem", "harem"),
            Pair("hegao", "hegao"),
            Pair("Hentai", "hentai"),
            Pair("High sexual content", "high-sexual-content"),
            Pair("High Vision", "high-vision"),
            Pair("Historical", "historical"),
            Pair("Hoksi", "hoksi"),
            Pair("Hoods Entertainment", "hoods-entertainment"),
            Pair("Horror", "horror"),
            Pair("Housewife", "housewife"),
            Pair("Huge Butt", "huge-butt"),
            Pair("Huge Dick", "huge-dick"),
            Pair("Humilation", "humilation"),
            Pair("Humiliation", "humiliation"),
            Pair("Humillation", "humillation"),
            Pair("Hypnostis", "hypnostis"),
            Pair("Hypnotis", "hypnotis"),
            Pair("Hypnotize", "hypnotize"),
            Pair("Idol", "idol"),
            Pair("ig Oppai", "ig-oppai"),
            Pair("Image Video", "image-video"),
            Pair("Incest", "incest"),
            Pair("Infidelity", "infidelity"),
            Pair("Inflation", "inflation"),
            Pair("Intercrural", "intercrural"),
            Pair("Isekai", "isekai"),
            Pair("JAV", "jav"),
            Pair("JK", "jk"),
            Pair("Josei", "josei"),
            Pair("Kiss", "kiss"),
            Pair("Kiss Kiss", "kiss-kiss"),
            Pair("L2D", "l2d"),
            Pair("Lactation", "lactation"),
            Pair("Lady", "lady"),
            Pair("LadyLove", "ladylove"),
            Pair("Licking", "licking"),
            Pair("Loli", "loli"),
            Pair("Loli. Paizuri", "loli-paizuri"),
            Pair("Lolicon", "lolicon"),
            Pair("Love", "love"),
            Pair("Love Polygon", "love-polygon"),
            Pair("Magic", "magic"),
            Pair("Magical Sex Shift", "magical-sex-shift"),
            Pair("Mahou Shoujo", "mahou-shoujo"),
            Pair("Maid", "maid"),
            Pair("Male Monster", "male-monster"),
            Pair("Married Woman", "married-woman"),
            Pair("Martial Arts", "martial-arts"),
            Pair("Masochist", "masochist"),
            Pair("Masturbation", "masturbation"),
            Pair("Mature Woman", "mature-woman"),
            Pair("Mecha", "mecha"),
            Pair("Megane", "megane"),
            Pair("MILF", "milf"),
            Pair("Military", "military"),
            Pair("Milky Animation Label", "milky-animation-label"),
            Pair("Mind Control", "mind-control"),
            Pair("Mini Skirt.", "mini-skirt"),
            Pair("Missionary", "missionary"),
            Pair("Mizugi", "mizugi"),
            Pair("Mizugi / Swimsuit", "mizugi-swimsuit"),
            Pair("Monogatari Series", "monogatari-series"),
            Pair("Monster", "monster"),
            Pair("Monster Girl", "monster-girl"),
            Pair("Mother", "mother"),
            Pair("MS Pictures", "ms-pictures"),
            Pair("Music", "music"),
            Pair("Mystery", "mystery"),
            Pair("Mythology", "mythology"),
            Pair("Nakadashi", "nakadashi"),
            Pair("Nasty", "nasty"),
            Pair("Nasty / Hard", "nasty-hard"),
            Pair("Netorare", "netorare"),
            Pair("Nipple Fuck", "nipple-fuck"),
            Pair("No Bra", "no-bra"),
            Pair("NTR", "ntr"),
            Pair("Nu", "nu"),
            Pair("Nurse", "nurse"),
            Pair("Office", "office"),
            Pair("Office Girl", "office-girl"),
            Pair("OL", "ol"),
            Pair("Old man", "old-man"),
            Pair("Older sister", "older-sister"),
            Pair("Onee-chan", "onee-chan"),
            Pair("Onee-san", "onee-san"),
            Pair("Oppai", "oppai"),
            Pair("Oral", "oral"),
            Pair("Oral sex", "oral-sex"),
            Pair("Orgasm", "orgasm"),
            Pair("Orgia", "orgia"),
            Pair("Orgy", "orgy"),
            Pair("Original Collab", "original-collab"),
            Pair("Original Collaboration", "original-collaboration"),
            Pair("Other Fetishes", "other-fetishes"),
            Pair("Paihame", "paihame"),
            Pair("Paizuri", "paizuri"),
            Pair("Pantyhose", "pantyhose"),
            Pair("Parody", "parody"),
            Pair("Pedophile", "pedophile"),
            Pair("Pedophile :v", "pedophile-v"),
            Pair("Pedophile :v Blowjob", "pedophile-v-blowjob"),
            Pair("Pee", "pee"),
            Pair("Pettanko", "pettanko"),
            Pair("Photograph", "photograph"),
            Pair("POV", "pov"),
            Pair("Pregnant", "pregnant"),
            Pair("Promiscuity", "promiscuity"),
            Pair("Prostitution", "prostitution"),
            Pair("Psychological", "psychological"),
            Pair("Rape", "rape"),
            Pair("Reincarnation", "reincarnation"),
            Pair("Rimjob", "rimjob"),
            Pair("Risky Mosaic", "risky-mosaic"),
            Pair("Role Play.", "role-play"),
            Pair("Romance", "romance"),
            Pair("Rough Sex.", "rough-sex"),
            Pair("Sadist", "sadist"),
            Pair("Sailor Uniform.", "sailor-uniform"),
            Pair("Saimin", "saimin"),
            Pair("Schoogirl", "schoogirl"),
            Pair("School", "school"),
            Pair("School Girls", "school-girls"),
            Pair("Schoolgirl", "schoolgirl"),
            Pair("Sci-Fi", "sci-fi"),
            Pair("Seinen", "seinen"),
            Pair("Semi-Hentai", "semi-hentai"),
            Pair("Semi-Rape", "semi-rape"),
            Pair("Sensei", "sensei"),
            Pair("Sex Toys", "sex-toys"),
            Pair("SexSlave", "sexslave"),
            Pair("Sexy", "sexy"),
            Pair("Shame", "shame"),
            Pair("Shaved", "shaved"),
            Pair("Shibari", "shibari"),
            Pair("Shibari / BDSM", "shibari-bdsm"),
            Pair("Shota", "shota"),
            Pair("Shounen", "shounen"),
            Pair("Single Work", "single-work"),
            Pair("Sister", "sister"),
            Pair("Slave", "slave"),
            Pair("Slender", "slender"),
            Pair("Slut", "slut"),
            Pair("Sluts", "sluts"),
            Pair("Solowork", "solowork"),
            Pair("Sousou No Frieren", "sousou-no-frieren"),
            Pair("Space", "space"),
            Pair("Spooning", "spooning"),
            Pair("Sports", "sports"),
            Pair("Squirt.", "squirt"),
            Pair("Squirting", "squirting"),
            Pair("Stocking", "stocking"),
            Pair("Stockings", "stockings"),
            Pair("Studio Fantasia", "studio-fantasia"),
            Pair("Succubus", "succubus"),
            Pair("Super Milk", "super-milk"),
            Pair("Super Power", "super-power"),
            Pair("Supernatural", "supernatural"),
            Pair("Supra Natural", "supra-natural"),
            Pair("Supranatural", "supranatural"),
            Pair("Suspense", "suspense"),
            Pair("Sweat", "sweat"),
            Pair("Swimsuit", "swimsuit"),
            Pair("Swimsuit / Mizugi", "swimsuit-mizugi"),
            Pair("Swimsuit / Mizugi Virgin", "swimsuit-mizugi-virgin"),
            Pair("Tall", "tall"),
            Pair("Teacher", "teacher"),
            Pair("Team Sports", "team-sports"),
            Pair("teen.", "teen"),
            Pair("Tentacle", "tentacle"),
            Pair("Tentacles", "tentacles"),
            Pair("Threesome", "threesome"),
            Pair("Titjob", "titjob"),
            Pair("Tits", "tits"),
            Pair("Titty fuck", "titty-fuck"),
            Pair("Toy", "toy"),
            Pair("Toy Sex", "toy-sex"),
            Pair("Toys", "toys"),
            Pair("Train", "train"),
            Pair("Tsundere", "tsundere"),
            Pair("Ugly Bastard", "ugly-bastard"),
            Pair("Ultra-Huge Tits", "ultra-huge-tits"),
            Pair("Uncensored", "uncensored"),
            Pair("Uncensored Exclusive Việt Nam Girl slutty Flight Attendant fucked in Hotel", "uncensored-exclusive-viet-nam-girl-slutty-flight-attendant-fucked-in-hotel"),
            Pair("Vampire", "vampire"),
            Pair("Vanilla", "vanilla"),
            Pair("Various Occupations", "various-occupations"),
            Pair("Vibrator", "vibrator"),
            Pair("Virgin", "virgin"),
            Pair("Voyeur", "voyeur"),
            Pair("Waitress", "waitress"),
            Pair("Watersports", "watersports"),
            Pair("Women on Top", "women-on-top"),
            Pair("Workplace", "workplace"),
            Pair("y Stockings", "y-stockings"),
            Pair("Yaoi", "yaoi"),
            Pair("Young wife", "young-wife"),
            Pair("Yuri", "yuri"),
        )

        val STUDIO = arrayOf(
            Pair("A-Real", "a-real"),
            Pair("Actas", "actas"),
            Pair("Ahegao", "ahegao"),
            Pair("Ai Yume Mai", "ai-yume-mai"),
            Pair("AIC", "aic"),
            Pair("AIC PLUS+", "aic-plus"),
            Pair("Aiko", "aiko"),
            Pair("Aiti St.", "aiti-st"),
            Pair("Amarcord", "amarcord"),
            Pair("animate Film", "animate-film"),
            Pair("Anime Antenna Iinkai", "anime-antenna-iinkai"),
            Pair("APPP", "appp"),
            Pair("Ark", "ark"),
            Pair("Arms", "arms"),
            Pair("Asahi Production", "asahi-production"),
            Pair("asread.", "asread"),
            Pair("AT-2", "at-2"),
            Pair("Atorie A.B.C.", "atorie-a-b-c"),
            Pair("AXsiZ", "axsiz"),
            Pair("Azeta Pictures", "azeta-pictures"),
            Pair("Big Oppai", "big-oppai"),
            Pair("Big Wing", "big-wing"),
            Pair("Blowjob", "blowjob"),
            Pair("Blue bread", "blue-bread"),
            Pair("Blue Cat", "blue-cat"),
            Pair("BreakBottle", "breakbottle"),
            Pair("Cafe de Jeilhouse", "cafe-de-jeilhouse"),
            Pair("Chaos Project", "chaos-project"),
            Pair("ChuChu", "chuchu"),
            Pair("Circle Tribute", "circle-tribute"),
            Pair("Collaboration Works", "collaboration-works"),
            Pair("Concept Films", "concept-films"),
            Pair("Creampie", "creampie"),
            Pair("Datama Film", "datama-film"),
            Pair("Diomedéa", "diomedea"),
            Pair("Dream Entertainment", "dream-entertainment"),
            Pair("Elf", "elf"),
            Pair("Enzo Animation", "enzo-animation"),
            Pair("Eshoya Honpo", "eshoya-honpo"),
            Pair("Ether Kitten", "ether-kitten"),
            Pair("Executive Decision", "executive-decision"),
            Pair("feel.", "feel"),
            Pair("Femdom", "femdom"),
            Pair("Flavors Soft", "flavors-soft"),
            Pair("Front Line", "front-line"),
            Pair("G-Lam", "g-lam"),
            Pair("Godoy", "godoy"),
            Pair("GoHands", "gohands"),
            Pair("GOLD BEAR", "gold-bear"),
            Pair("Gunners", "gunners"),
            Pair("Harem", "harem"),
            Pair("Himajin Planning", "himajin-planning"),
            Pair("Hoods Entertainment", "hoods-entertainment"),
            Pair("Horannabi", "horannabi"),
            Pair("Image House", "image-house"),
            Pair("Imagin", "imagin"),
            Pair("Irawias", "irawias"),
            Pair("Ishibashi Planning", "ishibashi-planning"),
            Pair("Jumondo", "jumondo"),
            Pair("Kami Kukan", "kami-kukan"),
            Pair("Kantou Douga Kai", "kantou-douga-kai"),
            Pair("Kazuki Production", "kazuki-production"),
            Pair("Kyushu Network Animation", "kyushu-network-animation"),
            Pair("Lilix", "lilix"),
            Pair("Maboroshi Koubou", "maboroshi-koubou"),
            Pair("Magic Bus", "magic-bus"),
            Pair("Majin", "majin"),
            Pair("Maplestar", "maplestar"),
            Pair("MB planning", "mb-planning"),
            Pair("Melissa", "melissa"),
            Pair("MILF", "milf"),
            Pair("MoMo Production", "momo-production"),
            Pair("Mook Animation", "mook-animation"),
            Pair("Mouse", "mouse"),
            Pair("Mousou Senka", "mousou-senka"),
            Pair("Mushi Production", "mushi-production"),
            Pair("Namu Animation", "namu-animation"),
            Pair("New Generation", "new-generation"),
            Pair("Nihikime no Dozeu", "nihikime-no-dozeu"),
            Pair("Nur", "nur"),
            Pair("Office AO", "office-ao"),
            Pair("Office No. 8", "office-no-8"),
            Pair("Office Take Off", "office-take-off"),
            Pair("Office Takeout", "office-takeout"),
            Pair("Okumaza", "okumaza"),
            Pair("ORADA COMPANY", "orada-company"),
            Pair("OUMA", "ouma"),
            Pair("Oz Inc.", "oz-inc"),
            Pair("Paizuri", "paizuri"),
            Pair("Passione", "passione"),
            Pair("Peak Hunt", "peak-hunt"),
            Pair("Piko Studio", "piko-studio"),
            Pair("Pink Cat", "pink-cat"),
            Pair("Poly Animation", "poly-animation"),
            Pair("PoRO", "poro"),
            Pair("PRA", "pra"),
            Pair("Production D.M.H", "production-d-m-h"),
            Pair("Queen Bee", "queen-bee"),
            Pair("Rabbit Gate", "rabbit-gate"),
            Pair("Raiose", "raiose"),
            Pair("Ripple Film", "ripple-film"),
            Pair("Ryuu M's", "ryuu-ms"),
            Pair("Schoolzone", "schoolzone"),
            Pair("SELFISH", "selfish"),
            Pair("Seven", "seven"),
            Pair("Shindeban Film", "shindeban-film"),
            Pair("Shinjukuza", "shinjukuza"),
            Pair("Shinkuukan", "shinkuukan"),
            Pair("Shion", "shion"),
            Pair("Shura", "shura"),
            Pair("Silver", "silver"),
            Pair("Sonsan Kikaku", "sonsan-kikaku"),
            Pair("Space-X", "space-x"),
            Pair("Staple Entertainment", "staple-entertainment"),
            Pair("Studio 1st", "studio-1st"),
            Pair("Studio 9 Maiami", "studio-9-maiami"),
            Pair("Studio Boogie Nights", "studio-boogie-nights"),
            Pair("Studio CA", "studio-ca"),
            Pair("Studio Deen", "studio-deen"),
            Pair("Studio Dolphin Night", "studio-dolphin-night"),
            Pair("Studio Eromatick", "studio-eromatick"),
            Pair("Studio Fantasia", "studio-fantasia"),
            Pair("Studio G-1Neo", "studio-g-1neo"),
            Pair("Studio Gadget", "studio-gadget"),
            Pair("Studio Gokumi", "studio-gokumi"),
            Pair("Studio Hokiboshi", "studio-hokiboshi"),
            Pair("Studio Jam", "studio-jam"),
            Pair("Studio Kyuuma", "studio-kyuuma"),
            Pair("Studio LEO", "studio-leo"),
            Pair("Studio March", "studio-march"),
            Pair("Studio Matrix", "studio-matrix"),
            Pair("Studio Prokion", "studio-prokion"),
            Pair("Studio Soul", "studio-soul"),
            Pair("Studio Ten", "studio-ten"),
            Pair("Studio Ten Carat", "studio-ten-carat"),
            Pair("Sugar Boy", "sugar-boy"),
            Pair("Suiseisha", "suiseisha"),
            Pair("Sunny Side Up", "sunny-side-up"),
            Pair("Suzuki Mirano", "suzuki-mirano"),
            Pair("T-Rex", "t-rex"),
            Pair("Teatro Nishi Tokyo Studio", "teatro-nishi-tokyo-studio"),
            Pair("Torudaya", "torudaya"),
            Pair("Triple X", "triple-x"),
            Pair("Tryforce", "tryforce"),
            Pair("UWAN Pictures", "uwan-pictures"),
            Pair("Virgin", "virgin"),
            Pair("XE", "xe"),
            Pair("Y.O.U.C", "y-o-u-c"),
            Pair("Zyc", "zyc"),
        )

        val SEASON = arrayOf(
            Pair("Big Oppai", "big-oppai"),
            Pair("Fellatio", "fellatio"),
            Pair("Gangbang", "gangbang"),
            Pair("Incest", "incest"),
            Pair("Paizuri", "paizuri"),
            Pair("Summer 2015", "summer-2015"),
            Pair("Summer 2021", "summer-2021"),
            Pair("Summer 2026", "summer-2026"),
            Pair("Winter 2019", "winter-2019"),
            Pair("Winter 2020", "winter-2020"),
            Pair("Winter 2022", "winter-2022"),
        )
    }}
}}
