ext {
    extName = 'Meownime'
    extClass = '.Meownime'
    extVersionCode = 2
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:pixeldrainextractor"))
    implementation(project(":lib:gdriveplayerextractor"))
    implementation(project(":lib:bloggerextractor"))
}
