package eu.kanade.tachiyomi.animeextension.id.alqanime

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

object AlqanimeFilters {
    open class UriPartFilter(
        displayName: String,
        private val vals: Array<Pair<String, String>>,
        defaultValue: Int = 0,
    ) : AnimeFilter.Select<String>(
        displayName,
        vals.map { it.first }.toTypedArray(),
        defaultValue,
    ) {
        fun toUriPart(): String = vals[state].second
    }

    class GenreFilter : UriPartFilter("Genre / Tag", GENRE_LIST)

    val FILTER_LIST: AnimeFilterList
        get() = AnimeFilterList(
            AnimeFilter.Header("Catatan: Filter genre hanya aktif jika pencarian teks kosong"),
            GenreFilter(),
        )

    private val GENRE_LIST = arrayOf(
        Pair("Semua", ""),
        Pair("Action", "action"),
        Pair("Adult Cast", "adult-cast"),
        Pair("Adventure", "adventure"),
        Pair("Anthropomorphic", "anthropomorphic"),
        Pair("Avant Garde", "avant-garde"),
        Pair("Award Winning", "award-winning"),
        Pair("Boys Love", "boys-love"),
        Pair("CGDCT", "cgdct"),
        Pair("Cars", "cars"),
        Pair("Childcare", "childcare"),
        Pair("Combat Sports", "combat-sports"),
        Pair("Comedy", "comedy"),
        Pair("Crossdressing", "crossdressing"),
        Pair("Delinquents", "delinquents"),
        Pair("Dementia", "dementia"),
        Pair("Demons", "demons"),
        Pair("Detective", "detective"),
        Pair("Donghua", "donghua"),
        Pair("Drama", "drama"),
        Pair("Ecchi", "ecchi"),
        Pair("Educational", "educational"),
        Pair("Erotica", "erotica"),
        Pair("Fantasy", "fantasy"),
        Pair("Gag Humor", "gag-humor"),
        Pair("Girls Love", "girls-love"),
        Pair("Gore", "gore"),
        Pair("Gourmet", "gourmet"),
        Pair("Harem", "harem"),
        Pair("Hentong", "hentong"),
        Pair("High Stakes Game", "high-stakes-game"),
        Pair("Historical", "historical"),
        Pair("Horror", "horror"),
        Pair("Idols (Female)", "idols-female"),
        Pair("Idols (Male)", "idols-male"),
        Pair("Isekai", "isekai"),
        Pair("Iyashikei", "iyashikei"),
        Pair("Josei", "josei"),
        Pair("Kids", "kids"),
        Pair("Korea", "korea"),
        Pair("Love Polygon", "love-polygon"),
        Pair("Love Status Quo", "love-status-quo"),
        Pair("Magic", "magic"),
        Pair("Magical Sex Shift", "magical-sex-shift"),
        Pair("Mahou Shoujo", "mahou-shoujo"),
        Pair("Malaysia", "malaysia"),
        Pair("Martial Arts", "martial-arts"),
        Pair("Mecha", "mecha"),
        Pair("Medical", "medical"),
        Pair("Military", "military"),
        Pair("Music", "music"),
        Pair("Mystery", "mystery"),
        Pair("Mythology", "mythology"),
        Pair("Organized Crime", "organized-crime"),
        Pair("Otaku Culture", "otaku-culture"),
        Pair("Parody", "parody"),
        Pair("Performing Arts", "performing-arts"),
        Pair("Pets", "pets"),
        Pair("Police", "police"),
        Pair("Psychological", "psychological"),
        Pair("Racing", "racing"),
        Pair("Reincarnation", "reincarnation"),
        Pair("Reverse Harem", "reverse-harem"),
        Pair("Romance", "romance"),
        Pair("Samurai", "samurai"),
        Pair("School", "school"),
        Pair("Sci-Fi", "sci-fi"),
        Pair("Seinen", "seinen"),
        Pair("Shoujo", "shoujo"),
        Pair("Shounen", "shounen"),
        Pair("Showbiz", "showbiz"),
        Pair("Slice of Life", "slice-of-life"),
        Pair("Space", "space"),
        Pair("Sports", "sports"),
        Pair("Strategy Game", "strategy-game"),
        Pair("Super Power", "super-power"),
        Pair("Supernatural", "supernatural"),
        Pair("Survival", "survival"),
        Pair("Suspense", "suspense"),
        Pair("Team Sports", "team-sports"),
        Pair("Thriller", "thriller"),
        Pair("Time Travel", "time-travel"),
        Pair("US", "us"),
        Pair("Urban Fantasy", "urban-fantasy"),
        Pair("Vampire", "vampire"),
        Pair("Video Game", "video-game"),
        Pair("Villainess", "villainess"),
        Pair("Visual Arts", "visual-arts"),
        Pair("Workplace", "workplace"),
    )
}
